# Generated by Django 5.0.4 on 2024-04-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callbreak', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomplayer',
            name='is_ready',
        ),
    ]
