# Generated by Django 5.0.4 on 2024-04-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbreak', '0003_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
