# Generated by Django 5.0.4 on 2024-04-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbreak', '0004_invitation_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomplayer',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
